apiVersion: apps/v1
kind: Deployment
metadata:
  name: amjam-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: amjam07/edureka_mlops_cicd_build_img_api:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: amjam-api-svc
spec:
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000
